[project]
name = "reliable-gasless"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.gasless-payment]
path = "contracts/gasless-payment.clar"
depends_on = []

[contracts.usage-metrics]
path = "contracts/usage-metrics.clar"
depends_on = []

[contracts.meta-subscription]
path = "contracts/meta-subscription.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
